name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write #Â added for provenance

    outputs:
      published: ${{ steps.changesets.changesets_output.published }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release'
          title: 'chore: release'
          publish: 'pnpm release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Output changeset result
        id: changesets_output
        if: ${{ steps.changesets.outputs.hasChangesets == 'false' }}
        run: echo "published=true" >> "$GITHUB_OUTPUT"

  documentation-build:
    name: Documentation build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs:
      - release
    if: ${{ needs.release.outputs.published }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build with VitePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  documentation-deploy:
    name: Documentation deploy
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - release
      - documentation-build
    if: ${{ needs.release.outputs.published }}
    
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  on-ci-fail:
    name: 'Failure'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'CI failed. Release won't be executed'
